name: Import Repositories


# Так це чат гпт, але я не хочу власно руч переносити тому ось


on:
  workflow_dispatch: # Дозволяє вручну запускати workflow

jobs:
  import_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout new repo
        uses: actions/checkout@v2
        with:
          repository: your_username/new_repo_name # замініть на новий репозиторій
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Import repo1 to branch_for_repo1
        run: |
          git remote add repo1 https://github.com/your_username/repo1.git
          git fetch repo1
          git checkout -b branch_for_repo1
          git merge repo1/main --allow-unrelated-histories
          git push origin branch_for_repo1

      - name: Import repo2 to branch_for_repo2
        run: |
          git remote add repo2 https://github.com/your_username/repo2.git
          git fetch repo2
          git checkout -b branch_for_repo2
          git merge repo2/main --allow-unrelated-histories
          git push origin branch_for_repo2

      # Додайте більше кроків для інших репозиторіїв
