name: Import Repositories

on:
  workflow_dispatch:

jobs:
  import_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout new repo
        uses: actions/checkout@v2
        with:
          repository: Vartem4got/Lab_Lib
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          persist-credentials: false


      - name: Configure Git user
        run: |
          git config --global user.name Vartem4got
          git config --global user.email artwitch3000@gmail.com
          

      - name: Setup GitHub authentication
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global credential.helper store
          echo "https://Vartem4got:${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials

      
      - name: Import lab1 to Lib_Lab_for_lab1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote add lab1 https://github.com/Vartem4got/lab1.git
          git fetch lab1
          git checkout -b lab1
          git merge -X theirs lab1/main --allow-unrelated-histories
          git push origin lab1

      - name: Import lab2 to Lib_Lab_for_lab2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote add lab2 https://github.com/Vartem4got/lab2.git
          git fetch lab2
          git checkout -b lab2
          git merge -X theirs lab2/main --allow-unrelated-histories
          git push origin lab2

      - name: Import lab3 to Lib_Lab_for_lab3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote add lab3 https://github.com/Vartem4got/lab3.git
          git fetch lab3
          git checkout -b lab3
          git merge -X theirs lab3/main --allow-unrelated-histories
          git push origin lab3

      - name: Import lab4 to Lib_Lab_for_lab4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote add lab4 https://github.com/Vartem4got/lab4.git
          git fetch lab4
          git checkout -b lab4
          git merge -X theirs lab4/main --allow-unrelated-histories
          git push origin lab4

      - name: Import lab5 to Lib_Lab_for_lab5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote add lab5 https://github.com/Vartem4got/lab5.git
          git fetch lab5
          git checkout -b lab5
          git merge -X theirs lab5/main --allow-unrelated-histories
          git push origin lab5

      - name: Import lab6 to Lib_Lab_for_lab6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote add lab6 https://github.com/Vartem4got/lab6.git
          git fetch lab6
          git checkout -b lab6
          git merge -X theirs lab6/main --allow-unrelated-histories
          git push origin lab6
